[graphics] draw_AUV for IPE
SimonRohou/tubex-lib pull request #126
Opened 2024-10-28 14:03 UTC by godardma

2024-11-05 09:31 UTC, godardma reviewed
ceci est un test

2024-11-05 09:32 UTC, SimonRohou requested changes
Finishing the first review

2024-11-05 09:32 UTC, SimonRohou commented on src/graphics/3rd/ipe/codac2_Figure2D_IPE.cpp
> +void Figure2D_IPE::begin_path_with_matrix(const Vector& x, float length, const StyleProperties& s)
Je n'ai pas compris le titre de cette fonction, ou ce qu'elle fait :)

2024-11-05 09:32 UTC, SimonRohou commented on src/graphics/3rd/ipe/codac2_Figure2D_IPE.cpp
> +  _f_temp_content << scale_x(c[0] + r.lb() * cos(theta.lb()).mid()) << " " << scale_y(c[1] + r.lb() * sin(theta.lb()).mid()) << " m \n";
Je pense qu'on peut factoriser ce code avec un calcul matriciel simple, avant l'écriture dans _f_temp_content.
Qu'en penses-tu ?

(ce n'est pas le cas dans VIBes, qui ne dispose pas de fonctionnalités de calcul matriciel)

2024-11-05 09:32 UTC, SimonRohou commented on src/graphics/3rd/ipe/codac2_Figure2D_IPE.cpp
> +  _f_temp_content << 1  << " " << -1.5  << " m \n";
À tester, mais l'écriture d'une chaîne de caractères connue dès la compilation est probablement plus rapide que l'ajout de caractères uniques dans un flux (mais sans certitude).

Quelque chose avec un constexpr, comme : 
```cpp
constexpr char tank_shape[] = " 1 -1.5 m \n -1 -1.5 l \n 0 -1.5 l \n 0 -1 l \n -1 -1 l \n -1 1 l \n 0 1 l \n 0 1.5 l \n -1 1.5 l \n 1 1.5 l \n 0 1.5 l \n 0 1 l \n 3 0.5 l \n 3 -0.5 l \n 0 -1 l \n 0 -1.5 l \n";
```

2024-11-05 09:32 UTC, SimonRohou commented on src/graphics/3rd/ipe/codac2_Figure2D_IPE.cpp
>  using namespace std;
test

2024-11-05 09:38 UTC, godardma commented on src/graphics/3rd/ipe/codac2_Figure2D_IPE.cpp
> +void Figure2D_IPE::begin_path_with_matrix(const Vector& x, float length, const StyleProperties& s)
Pour les véhicules (draw_tank et draw_AUV) le header par défaut du begin_path n'est pas suffisant. J'ai donc ajouté cette fonction qui fait le même travail que le begin_path, avec en plus le champ "matrix" complété. 

Ce champ contient 6 valeurs : les 4 premières sont la matrice de transformation 2D, rotation et dilatation, "par colonne" (i.e. m11, m21, m12, m22) et les 2 autres valeurs sont la translation. Le tout permet de scale le véhicule, l'orienter et le déplacer au bon endroit. 

Cette fonction écrit dans le xml quelque chose dans le style : 
     <path layer="alpha" 
     stroke="codac_color_000000" 
     fill="codac_color_ffd32a" 
     opacity="100%" 
     stroke-opacity="100%" 
     pen="heavier" 
     matrix="0.00948009 11.9048 -11.9047 0.00948009 166.667 166.667">

2024-11-05 09:39 UTC, godardma commented on src/graphics/3rd/ipe/codac2_Figure2D_IPE.cpp
> +void Figure2D_IPE::begin_path_with_matrix(const Vector& x, float length, const StyleProperties& s)
<path layer="alpha" 
     stroke="codac_color_000000" 
     fill="codac_color_ffd32a" 
     opacity="100%" 
     stroke-opacity="100%" 
     pen="heavier" 
     matrix="0.00948009 11.9048 -11.9047 0.00948009 166.667 166.667">

2024-11-05 10:05 UTC, godardma commented on src/graphics/3rd/ipe/codac2_Figure2D_IPE.cpp
> +  _f_temp_content << 1  << " " << -1.5  << " m \n";
ça ne coûte rien d'essayer ! c'est fait dans mon dernier commit

2024-11-05 10:36 UTC, godardma commented on src/graphics/3rd/ipe/codac2_Figure2D_IPE.cpp
> +  _f_temp_content << scale_x(c[0] + r.lb() * cos(theta.lb()).mid()) << " " << scale_y(c[1] + r.lb() * sin(theta.lb()).mid()) << " m \n";
J'ai tenté de réécrire cette fonction plus "proprement" en définissant clairement les 4 points du pie. Je ne sais pas si il y a possibilité de factoriser beaucoup plus car il y a les histoires de scaling (x, y et length), et suivant les points on prend soit le lb() du rayon, le ub() de theta etc...
Ceci dit si tu as une idée pour faire ça en moins de lignes je suis preneur !

2024-11-06 08:00 UTC, SimonRohou commented on src/graphics/3rd/ipe/codac2_Figure2D_IPE.cpp
> +void Figure2D_IPE::begin_path_with_matrix(const Vector& x, float length, const StyleProperties& s)
Ok c'est très clair !

2024-11-06 08:00 UTC, SimonRohou commented on src/graphics/3rd/ipe/codac2_Figure2D_IPE.cpp
> +  _f_temp_content << scale_x(c[0] + r.lb() * cos(theta.lb()).mid()) << " " << scale_y(c[1] + r.lb() * sin(theta.lb()).mid()) << " m \n";
En fait, mon commentaire n'a plus lieu d'être maintenant que j'ai compris la réponse à ma précédente réaction.

2024-11-06 08:03 UTC, merged